### ISSUE TITLE
query method with variadic

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Trestle#11]
Currently, the query method accepts two arguments: `$query` and `$binds`. I thought about adding the possibility to replace the `$binds` array with variadic ([func_get_args()](http://php.net/manual/en/function.func-get-args.php) for PHP 5.4).

I peeked at [mysqli::query](http://php.net/manual/en/mysqli.query.php) to check if there could be a third parameter. `mysqli::query` does have `$resultmode`, but to be honest, I'm not sure what it does. Googling this didn't really get me any results.

The question is: is there possibly coming a third parameter in the future? If not, I think it's nice to be able to do this:
```php
$sql = 'SELECT * FROM `table_name` WHERE `column` = ? AND `column_two` = ?';

$db->query($sql, $val1, $val2)
   ->exec();
```
instead of this:
```php
$sql = 'SELECT * FROM `table_name` WHERE `column` = ? AND `column_two` = ?';

$db->query($sql, [$val1, $val2])
   ->exec();
```
Being able to provide an array like now would be nice as well.

**Comment by FireDart** [comment]
I have been thinking about this for a couple of days and while I do like the idea I don't think I'm going to replace it with the array.

We use the array method between all the other CRUD methods and having a few using variadic and other not seems kind of weird. I would also want to do it with the offical `...` rather then `func_get_args()` because it feels hack-ish. PHP 5.6 is way off from complete support and only has like 0.5% market share (estimated).
