### ISSUE TITLE
No error if table doesn't exist.

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Trestle#2]
If a database table doesn't exist, you have to manually seek for errors. I didn't check this for the database name and database table columns, but they probably also don't show errors.

To get more information about the error, I had to run `$content->debug()`, which is confusing.

**Expected behavior:**
Exception message thrown like "Table '`database`.`table`' doesn't exist".

**Actual behavior:**
`bool(false)` returned.

**Additional info:**
The config includes:
```php
'display_errors' => true,
```

What does `display_errors` actually do?

**Comment by FireDart** [comment]
`display_errors` enables `PDO::ATTR_ERRMODE` & `PDO::ERRMODE_EXCEPTION`. I found this to be kind of usless and has been changed in firedart-dev. Pull request coming soon.

**Comment by pedzed** [comment]
Could you show errors then? Keep having to run the `debug` method too see what's wrong is a bit annoying. A configuration like this would be nice:
```php
'silence_errors' = false,
```
I don't know, be creative.

**Comment by FireDart** [comment]
Sorry, they way I wrote it seems to give off the wrong idea. `display_errors` still exists however instead of just handling PDO_Error it does Database connection, PDO error, query error, syntax, etc... and you can enable disable it.

**Comment by pedzed** [comment]
> `display_errors` still exists however instead of just handling PDO_Error it does Database connection, PDO error, query error, syntax, etc... and you can enable disable it.

Isn't it better to name it differently? I think it's confusing. Let's say that somebody uses Trestle in Tres Framework. The framework catches all exceptions, so "display_errors" (or "display_exceptions" actually) doesn't make sense.

What about:
```php
'throw_exceptions' = true
```
Or can't you just remove it? Why hide stuff anyway? Just show as many exceptions as you can (where applicable of course). Developers can always catch them.

**Comment by FireDart** [comment]
I should probably expand again, in the dev it is
```php
    'display_errors' => [
        'query' => false,
    ],
```

I'm going to added other ones as well, instead of throwing an exception you might want to suppress everything and only log it and display a generic message like "Unable to fulfill database request, try again" and then check the logs for specific issues.

I'm still experimenting with a proper mix and the reason why I have not pushed 0.2 to mainline yet, but the 0.2 is better then 0.1 I.M.O.

While I understand wanting to see all the messages, for security some people might want a way to suppress everything regardless, however, nothing will be permanently suppressed and you will always be able to see them if you enable it.

I will look into a better naming if I see fit.

**Comment by pedzed** [comment]
> for security some people might want a way to suppress everything regardless

```php
set_error_handler(function($e){});
set_exception_handler(function($e){});
```
?

Covers anything (except fatal of course).

Can you at least rename it? "Throw" errors,  "generate" errors, or whatever, but not "display" errors. Display means to me that you are going to show them like [Whoops](https://github.com/filp/whoops).

I also get confused about errors/exceptions. It doesn't really fit in one variable in my opinion.

**Comment by FireDart** [comment]
With the way errors are thrown in 0.2 dev a message like this should appear
> Trestle\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'trestle_1.table_no_exists' doesn't exist

As long as `throw/query` is set to `true`.
```php
'throw' => [
    'database' => true,
    'query'    => true,
],
```
Otherwise it will be suppressed.

If `throw/database` is set to `true` it will show something like:
> Trestle\TrestleException: Trestle could not connect to the database. SQLSTATE[HY000] [1049] Unknown database 'trestle_13'

Otherwise it will suppress and only log it,.

If the settings are set to `false` then `->debug()` should be used as that is the intended reason, to debug the error.

I'm considering this issue closed due to the following commits:
* 539c8e66e49e3bed99e91252b68ed16548bef8b8 (sorta)
* 539c8e66e49e3bed99e91252b68ed16548bef8b8
