### ISSUE TITLE
Post-execution methods

### ISSUE THREAD

**Issue by pedzed** [tres-framework/trestle#5]
I have been using Trestle for a while lately, but I still don't really feel comfortable with the available methods after execution. Think about `first()`, `results()`, `count()`, etc.

@julianrichen  have you thought about allowing the developer to use the PDO extension? [PDOStatement](http://php.net/manual/en/class.pdostatement.php) methods to be more precise.

If you rather make your own methods, could you at least add some more? Also, stuff like fetch style (array/object/...) are missing.

I personally would be more comfortable with `fetch()` and `fetchAll()`. I am more used to `numRows()` (or even the PDO `rowCount()` method), but `count()` is fine I suppose.

```php
$query = $this->_db->get('table')
                   ->where('x', '=', $y)
                   ->exec();

echo $query->numRows().' result'.($query->numRows() === 1) ? 's' : '').' have been found!';

echo '<pre>', print_r($query->fetch()), '</pre>';
```
What are your opinions about it?

**Comment by FireDart** [comment]
Added support for `PDO::*` using `results()` & `result()` with commit 6a490c4feb. `first()` as been deprecated,

Default mode is FETCH_OBJECT
```php
$query = $db->query('. . .');
$query->results(PDO::FETCH_ASSOC);
//or 
$query->result(PDO::FETCH_ASSOC);
```

**Comment by pedzed** [comment]
How will this work for methods like `create()`, `update()` and `delete()`?

Also, I am not really a fan of "result/results". It doesn't make much sense. A result is a result. It can contain multiple records: because that is the result.

**Comment by julianrichen** [comment]
We could go back to the original `first()`, `results()` & `count()`. `result()` would be what it was first called `first()`.

Will look into `create()`, `update()` and `delete()`.

**Comment by pedzed** [comment]
I propose to name them as `first()`, `all()` and `count()`. I am more of a fan of `firstResult()` and `allResults()` because it's more descriptive, but I believe that people would prefer the former. Also, the latter would make `count()` inconsistent. Whether you choose `count()` or `resultCount()`, it's both a no-go. `countResults()` is weird to me. Imagine it for example in if-statements.

Should we implement `last()` as well? It's really easy and consistent. If you have `first()`, why wouldn't you have `last()`?

**Comment by julianrichen** [comment]
Branching off from what you said in #27 we could do `records()`, `firstRecord()`, `lastRecord()` & `count()`, however, I believe it should only be one word because it is quicker to type. `first()`, `all()`, `last()` & `count()` work but is `results()` and `result()` really that flawed? My main concern is if all, first, last & count flow in a statement and can be read out of context and still explain the action? Examples:

``` php
$search = $db->read('articles')->where('title', 'LIKE', $userSearch)->exec();

$search->results();
$search->result();
// or
$search->all();
$search->first();
```

Both work well, however, `$search->all()` sounds like I'm searching the database at that movement (if out of context).

``` php
$user = $db->read('users')->where('id', '=', 1337)->exec();

$user->result();
// or 
$user->first();
```

Again both work but `$user->first();` sounds a little funny, the first what? The first user (like id = 1)? or the first result of that user query (id = 1337)? Where as `$user->result();` is the singular result from the user search.

``` php
$article = $db->read('articles')->limit(10)->offset(5)->exec();

$article->results();
// all
$article->all():
```

Again both work but if I was reading this out of context and I saw `$article->all():`, what is all? If the method was `allResults` it would be clear but that's longer and multi-worded compared to `results()`.

No matter the instance you know `results()`/`result()` will return result(s) because the word result(s) can stand on it's own. The word "all" can't stand on it's own because when I say "all" it does not describe anything, similar to the issue with `last()`. This is the main reason why I'm reserved on implementing `last()` and consider it vague.

I'm in favor of `results()`, `result()`, `count()` & `lastInsertId()`. lastInsertId is long but at least it's already common because of PDO.

I really wish we had a third or fourth person to provide input, someone not working on the project that can provide feedback on a user level.

**Comment by vasil7112** [comment]
Hello,
Just a random user here.

As it goes for your database script structure here is what i would prefer:
- As small commands as possible (e.x count() over countResults() / resultsCount())
- The commands name should be able to look as identical to their primary database as possible. So for people who will be using MySQLi database could have an alias for $db->read('articles') such as $db->select('articles').
- As for last which is the resultCount() problem you have. I would prefer as a developer a countResult() function. That is because with the autocomplition software (such as the one implemented in netbeans) i can write count and it could autofill every possible solution. That could help you later in case you have multiple count types (none that i can think of, but you might have an idea for the future) such as countResult() / countPotatos() / countConnections() / countExample(). As result not only the user can find easily a "count" function but at the same time he might find some extra functions that can help him solve an issue in the future.
- Also for the offset(x). I think it would be easier for the end-user to use a constructor such as limit($start, $end).

**Comment by rigor789** [comment]
``` PHP
$search = $db->read('articles')->where('title', 'LIKE', $userSearch)->exec();

$search->results();
$search->result();
// or
$search->all();
$search->first();
```

> Both work well, however, $search->all() sounds like I'm searching the database at that movement (if out of context).

That's a valid point in this example, but the example seems flawed.

``` PHP
$results = $db->read('articles')->where('title', 'LIKE', $query)->exec();
// and then
$results->first();
$results->all();
```

So, personally, I wouldn't call query results like `$user` since user is singular, and doesn't make much sense. I'd rather call it `$result` or an even more suitable name, I can't think of right now.

_Also, a side note:
For the models, I personally prefer delegating the common methods to another class, plus Active record type of models are much more convinient to use.
Maybe, entities could be used too. Simple DTO's in fact, that hold the db schema, and an underlying DB layer, can update the db based on that (via reflection, I suppose)._

**Comment by julianrichen** [comment]
First thank you both for the feedback.

> The commands name should be able to look as identical to their primary database as possible. So for people who will be using MySQL database could have an alias for $db->read('articles') such as $db->select('articles').

I really like this point, I played around with it for a while and you can now alias methods with commit 295fa63d32d5b9c5555372683cb98cd25f33b3df. For example trestle sees the following as the same for MySQL:

``` php
$db->read('table')->exec();
$db->select('table')->exec();
```

So you can use the native keyword instead of Trestle's syntax.

For results/result/all/first you can use either at any time, so the following is the same:

``` php
$search = $db->read('search')->where('title', 'LIKE', $query)->exec();
$results = $db->read('search')->where('title', 'LIKE', $query)>exec();

$search->results();
$results->all();
```

Pick whatever sounds better, using aliasing over real methods will slims down on code since we don't need to replicate methods.

Does this approach sound good?

---

On another note, this change will also be the initial commit to allow specific sql syntax functions like min, max & avg since method validation is now based of each blueprint instead of the basic `['query', 'create', 'read', 'update', 'delete', 'raw']` which was done in Database.php. Ex:

``` php
$db->read('students', ['id', $db->avg('grade')])
    ->exec();
```

Also ignore the failed commit before the one included above, was ammending a commit message and failed -_-

**Comment by pedzed** [comment]
> Pick whatever sounds better, using aliasing over real methods will slims down on code since we don't need to replicate methods.
> 
> Does this approach sound good?

In my opinion, most definitely not. Using two methods which do exactly the same, also known as aliasing, is a bad design.

First of all, you're admitting that you couldn't design it in a better way. So, what you're telling is:

> Because this isn't well thought out, I give you the option between A and B. They do exactly the same though.

It's like parents not being able to agree on one name, so they add another.

Anyway, this is not much of a problem. I mean, nobody cares that you can't come up with something better, right? The second point I am going to make is in fact really important.

Remember when you started with PHP and saw `die()` and `exit()` and had to look online [what the difference was](http://stackoverflow.com/a/1795031)? For everything you have to search online, you are wasting some valuable time you can better spend on programming.

It is confusing and increases inconsistency. More things have to be documented, people will search and waste their time more and more things have to be read. Reading code just gets harder because of all the possibilities.

So my conclusion is no. I highly disagree on aliasing.

The methods are fine as they were: `create()`, `read()`,  `update()` and `delete()`. Easy to remember if you think about "CRUD".

Also, I my vote goes to `first()`, `last()`, `all()` and `count()`.

**Comment by vasil7112** [comment]
Sure, using aliasing IS a bad design. But when it comes to designing a program you can't always stay with the most commons designs.

Designs where created for simplicity and performance. Although i mostly agree with designs, i strongly believe that always following them may cause the loss of creativity for "new designs" to be approched.

When you are building a product for the end-user, you can't only think about the best design options, but also the best ways to make your end-user comfortable with.

Here is an example: I am/was also a bukkit developer for Minecraft Applications. I had created a plugin called PortableTent. You could use the following command to access the help menu: /portabletent. Yes, it seems pretty straight forward. But, i noticed that most of my users where using the aliacing system i had created. They could simply change the /portabletent as well as any command included with a simple alias. Most of them ended up using the following 2. /ptent and /pt.

Although this example has nothing to do with MySQL or PHP, i just wanted to show you that if you create a succesful aliancing system you can allow your users to be more comfortable with your program. At the same time, they might create of "function names" to execute your functions which could result in them spending less time in the end writing the program.

For example they could had made an alias for the function countResults() (which could be your default function) as count(), or even read() to select().

The perfect solution would be to add a tool, (probably with reflection for PHP), that can allow your users to create an alias for every function in your project.

Just remember, you are not creating a framework that can run as fast as possible, and have the best design as possible. You are creating a framework that your user will chose because they like it, and feel comfortable with.
If the above was not the reason you created this software, and the reason was to create the fastest as possible framework, you shouldn't even start thinking php, but c++. Such as these guys: http://phalconphp.com/en/

Anyways, sure, not all opinions will be the same. Just chose the one that you and your customers will be most comfortable with.

**Comment by pedzed** [comment]
> They could simply change the /portabletent as well as any command included with a simple alias. Most of them ended up using the following 2. /ptent and /pt.

It's not quite the same. I think the difference between a new name and a shorter version is quite important. `read()` and `select()` are totally different, whereas `num` and `number`, `int` and `integer`, `db` and `database`, etc. are obvious.

@vasil7112 In your example, when talking about CLI's (Command Line Interfaces), I agree that it's nice to have "abbreviation aliases", but we are talking about pseudonyms here.

``` bash
-h  --help
-v  --version
# ...
```

**Comment by julianrichen** [comment]
Are we using `last()` as `lastInsertId()` or as the last row in the query? If the latter it seems this is the best option if you enable `PDO::CURSOR_SCROLL`:

``` php
return $this->statement->fetch(PDO::FETCH_NUM, PDO::FETCH_ORI_LAST);
```

Gonna hold off on this till I play around with it more, not sure if `PDO::CURSOR_SCROLL` has unexpected results on another queries since it is applied on the prepare method.

**Comment by pedzed** [comment]
> Are we using `last()` as `lastInsertId()` or as the last row in the query?

Definitely not as an alias, as I pointed earlier that I am against aliasing with the reasoning behind it.

I originally came up with `last()` to get the last row from the query:

> Should we implement last() as well? It's really easy and consistent. If you have first(), why wouldn't you have last()?

**P.S.** I thought of simply [getting the last element in the results array](https://stackoverflow.com/questions/3687358/best-way-to-get-last-element-of-an-array-w-o-deleting-it), but now I see why that that's not a great idea.

**Comment by pedzed** [comment]
I'm getting second thoughts about `last()` now. @julianrichen can you come up with a good reason why one might use `last()`?

Now I am thinking about it, it seems to be totally useless. The only difference between `first()` and `all()` is that the former returns a flat array, whereas the latter returns a multidimensional array, correct?

Then `last()` would be useless, because one could for example add `->order('id', 'DESC')` and call `first()`.

**Comment by julianrichen** [comment]
I'm sure there is an individual out there that _could_ be using it for a very vague project but for general user, no. If it was something critical I'm sure PDO would have a built in method instead of using the impractical `PDO::ATTR` feature.

We could provide it just to be well rounded but again I would need to do testing `PDO::CURSOR_SCROLL` because I never used it.

Maybe better to leave it out and in the future (if trestle takes off and) if a user submits an issue about not having that feature we could add it.

**Comment by julianrichen** [comment]
Considering this closed since we addressed the major issues.
